environment:
  CIRRUS_WORKING_DIR: "/tmp/criu"
container:
  # This test case does not work on focal, because the newer version
  # of libvirt fails during 'vagrant up' with ip6tables errors.
  image: ubuntu:bionic
  kvm: true
  cpu: 4
  memory: 8G
task:
  name: Vagrant Fedora based test (no VDSO)
  setup_script: |
    scripts/ci/apt-install make gcc pkg-config git perl-modules iproute2 kmod wget
    ln -sf /usr/include/google/protobuf/descriptor.proto images/google/protobuf/descriptor.proto
  build_script: |
    make -C scripts/ci vagrant-fedora-no-vdso
